import os

from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL_NAME = os.getenv("OPENAI_MODEL_NAME")
OPENAI_MODEL_TEMPERATURE = float(os.getenv("OPENAI_MODEL_TEMPERATURE", "0"))

IA_CONTEXTUALIZE_PROMPT = os.getenv("IA_CONTEXTUALIZE_PROMPT")
IA_SYSTEM_PROMPT = os.getenv("IA_SYSTEM_PROMPT")

VECTOR_STORE_PATH = os.getenv("VECTOR_STORE_PATH")
RAG_FILES_DIR = os.getenv(("RAG_FILES_DIR"))

EVOLUTION_API_URL = os.getenv("EVOLUTION_API_URL")
EVOLUTION_INSTANCE_NAME = os.getenv("EVOLUTION_INSTANCE_NAME")
EVOLUTION_AUTHENTICATION_API_KEY = os.getenv("AUTHENTICATION_API_KEY")

REDIS_URL = os.getenv("CACHE_REDIS_URI")

BUFFER_KEY_SULFIX = os.getenv("BUFFER_KEY_SULFIX")
DEBOUNCE_SECONDS = float(os.getenv("DEBOUNCE_SECONDS", "0"))
BUFFER_TTL = int(os.getenv("BUFFER_TTL", "0"))

NUMBER_MESSAGE_RECEIVER = os.getenv("NUMBER_MESSAGE_RECEIVER")
